### ISSUE TITLE
Still under development?

### ISSUE THREAD

**Issue by rehno-lindeque** [dmbarbour/haskell-vcache#3] opened 2015-10-10 19:35 UTC
I notice that development on `vcache` seems to have died down lately. Are you still working on it? I felt that this might turn out to be a very nice package, it'd be a shame to see it stagnate... (are there other options aside from `tcache` and `acid-state`?)

**Comment by Ericson2314** [comment] 2015-10-22 04:06
I am wondering the same, this is really cool! I'd love to write multiple back-ends like https://github.com/mirage/irmin 's

**Comment by dmbarbour** [comment] 2015-11-10 22:35
VCache is in use. There isn't much more to 'develop' except for performance enhancements and minor bugfixes. I could probably bump the version number to 1.0. Except, all that 'semantic versioning' advice says not to bump a major version unless there is a big change in the API.

There are some performance enhancements I'd like to try. I'll add them as feature requests.

Apologies for not getting to this earlier. I was rather ill the second week of October, and I must have missed your query when attempting to catch up.

**Comment by dmbarbour** [comment] 2015-11-10 22:59
@Ericson2314 Developing multiple backends for VCache is entirely feasible. I would probably use a typeclass for types that implement the VCache API, and change the definition of `VCache` to an existential `newtype VCache = (ImplementsVCacheAPI a) => VCache a`. This could be done transparently, more or less.

OTOH, I personally have very little interest or motivation to develop these backends. The LMDB backend is a few orders of magnitude more than scalable enough for my foreseeable use cases.  

Irmin seems pretty cool! I hadn't heard of it.

**Comment by Ericson2314** [comment] 2015-11-10 23:09
The backend I'd be most interested in is https://ipfs.io/. Only something like that works for for distributed systems on adversarial networks.

The aspect of Irmin that I'd think would be useful/necessary for that is more separation between the immutable and mutable worlds.

**Comment by dmbarbour** [comment] 2015-11-11 01:18
@Ericson2314 I know a lot about distributed systems on adversarial networks. IPFS looks like an interesting approach, and I certainly favor the use of securely content-addressed networking.

I assume a proper integration would mean that individual values and variables (VRefs and PVars from VCache) are addressable and linkable on IPFS. This would severely complicate GC and degrade performance. But it's doable. Tolerable? I don't know.

An improper integration would involve me running VCache over LMDB over an mmap'd file on a mounted IPFS partition. Sadly, it'd probably have better performance, too.

**Comment by Ericson2314** [comment] 2015-11-11 02:33
> I know a lot about distributed systems on adversarial networks.

Wonderful.

> IPFS looks like an interesting approach, and I certainly favor the use of securely content-addressed networking.
I assume a proper integration would mean that individual values and variables (VRefs and PVars from VCache) are addressable and linkable on IPFS.

Yeah I am more sold on the general concept than the exact specifics of IPFS.

What concerns me is that a distributed content addressable store really just ought to support `VRefs`. IPFS's IPNS [I'm still unclear if they want the name "IPFS" to apply just to the thin waist or the whole stack] slaps some public-key cryptography on top, but that's just one possible solution.

As far as I can tell, supporting "VRef only" back ends, "PVar only" backends, and "PVar given VRef Backend" backends would necessitate some less trivial changes to this library's interface. Doing so without compromising combined backends like LMDB is an  challenge.

> I know a lot about distributed systems on adversarial networks

I have a sense that my sentence "Only something like that works for for distributed systems on adversarial networks." came off as naive or dismissive. If so, I am sorry. What I meant to say with that content-addressing is one of the least-leaky abstractions in the realms of storage and networking. It may not offer the best performance trade-offs in all circumstances, but I'd wager its easier to use and more closely aligned with most applications than the popular protocols and formats out there.

> This would severely complicate GC and degrade performance. But it's doable. Tolerable? I don't know.
An improper integration would involve me running VCache over LMDB over an mmap'd file on a mounted IPFS partition. Sadly, it'd probably have better performance, too.

I get the sentiment, but as I am more interested in the richness of data than its quantity, and the ability for two nodes to discover the data they have in common, I think that would be counter-productive.

**Comment by dmbarbour** [comment] 2015-11-11 16:36
@Ericson2314 
> a distributed content addressable store really just ought to support VRefs. 

Well, there's a good case for modeling mutable state. But it could be rooted at the toplevel, e.g. in a distributed hashtable or namecoin system or whatever.

I included anonymous `new` PVars in VCache mostly because I believed it was thematically appropriate for Haskell (e.g. Haskell already has TVars, MVars, IORefs, STRefs, ...). It certainly isn't essential to my own work on Wikilon. (Originally, VCache was just going to be part of Wikilon.) In general, I'd be happy to [push all mutable variables to a toplevel](https://awelonblue.wordpress.com/2012/10/21/local-state-is-poison/) and rely on spatial partitioning models (e.g. like URLs) to manipulate just part of a value. A lot of my designs have this as a common theme.

Of course, given rooted (access by name) PVars, it's trivial enough to *model* PVars by simply assigning each one a securely randomized URL that doesn't conflict with the existing ones. But then you also need to *model* the garbage collector for them. So this behavior is subtly discouraged by situational pressures. It's much easier to manage memory by allocating/deleting/resetting whole 'subdirectories'.

> more interested in the richness of data than its quantity

Quantity has a richness of its own! Try viewing the web with a 192x108 pixel monitor instead of a 1920x1080, and you'll quickly understand the continuum fallacy. ;)

The reason I'm not interested in integrating VCache with this layer is that VCache is primarily a **value**  caching library: i.e. there are no **data** semantics to a VRef. The number 708 is a value. But to turn it into data, I need context like "there are 708 apples on my table, WTF?!". VRef's primary purpose is to support larger-than-memory values. Rooted PVars further allow *durability* of values. Anonymous PVars are a convenient gimmick to better leverage the GC or widen the STM bottleneck. 

With VCache, the context is implicit to the application. VCache is not a database. It's just a scalability tool.

I'd be far more inclined to integrate with IPFS at a higher application layer.

**Comment by Ericson2314** [comment] 2015-11-11 18:06
Exactly for the sake of not compromising "compromising combined backends like LMDB" I'd want to keep anonymous `PRefs`. Just as one can model anonymous `PVars` with randomly named ones, it that can just be an implementation detail for backends that need it.

I've thought a little bit about how GC code code be shared between IPFS and LMDB backends, but there is nothing wrong with defining an interface and sharing no implementation to begin in order to prevent performance regressions.

By "a distributed content addressable store really just ought to support VRefs" I mean that fundamental a content addressable store only holds immutable data. Since there are many possible ways to add support for mutable data on top, it seems to me improper to "canonize" one of them in a combined instance.

>  ...there are no data semantics to a VRef...

If I understand correctly, I think we have the same goals. I don't want to enforce or even remember schemata, but just let the type system do its job, which I believe is what VCache (and Irmin) do already.

**Comment by dmbarbour** [comment] 2015-11-11 23:40
> By "a distributed content addressable store really just ought to support VRefs" I mean that fundamental a content addressable store only holds immutable data. Since there are many possible ways to add support for mutable data on top, it seems to me improper to "canonize" one of them in a combined instance.

Ah, I thought you were saying: "a distributed content addressable store should be *just barely powerful enough* to support VRefs". Which roughly corresponds to: ALL content is addressed by secureHash(SerializedValue).

If you allow content addressing by anything more than a string that is opaque and unrelated to the value, you support more than VRefs.

**Comment by Ericson2314** [comment] 2015-11-12 03:27
Ah good, I think we are bit more on the same page now :).

> If we allow content addressing by anything more than a string that is opaque and unpredictable unless you already have constructed the value (for structure sharing and fast equality), you support more than just VRefs. But if this is all you have, all of those "many possible ways to add support for mutable data on top" are infeasible.

Let me lay out my rough ideas:

1. For the `VRef`-only layer, I was considering hashing everything that is put/gotten, so yes the value does need to be fully known (by someone) to reference it.

2. `PVar`s would just stored as names, but either could exist in memory with the underlying `TVar`, or there could be some "extra trace hook" to keep their current pointee alive during GC. Not really sure which is conceptually cleaner, but the former sounds much more performant.

3. With `PVar`s in place, it should be possible to make thunks with caching. MapReduce, meet the Spineless Tagless G Machine!

Implementation wise:

1. there could be a `class ImmutPut` and then a `class ImmutPut => MutPut`, and likewise for get. On the other hand, I think `instance (ImmutCacheable a) => MutCacheable a` would be more useful.

2. Unless I am missing, the notion of a `VSpace` isn't so useful for the VRef-only layer, so I'd make it an associated type and define it as `()` for that layer.

**Comment by dmbarbour** [comment] 2015-11-12 06:16
With a content-addressable data store, we usually have more than one way to address data by content. E.g. we can use data that has a topic line, and allow searching for that topic. (We can still use a unforgeable topic name.) With just that much, we can model PVars directly "on top" of our content-addressable data store (though not efficiently). 

Sounds to me like you're modeling them elsewhere entirely. On top of TVars. Quite feasible, yeah. :)

I'm not tracking your thoughts well enough with the `ImmutPut` and such. You've probably spent some time thinking about it. I suggest you sketch your API if you're interested in more than this hand-wavy discussion.

The notion of a space, however you model it, is useful because we'll certainly have more than one 'content addressable data store' in the end, each using slightly different algorithms, promoted by different corporations or trying to protect themselves from government spies or whatever. But I agree you can model it with an associated type in Haskell, so our typeclass can provide our initializers and whatever global state we need for binding.

**Closed** 2015-11-13 19:19 UTC

**Comment by Ericson2314** [comment] 2015-11-13 19:38
I'd be glad to write up a more explicit proposal, just been busy since my last post. Should I open a separate issue for that?

**Comment by rehno-lindeque** [comment] 2015-11-13 23:18
Thank you for the kind response. Could you imagine using vcache as a session store in a production environment? I'm after a light weight "Redis as a library" (but only really for the sake of curiosity at this point).

Please excuse my rather mundane question following the interesting discussion that preceded it!
